### ISSUE TITLE
where is the documentation of bioGo?

### ISSUE THREAD

**Issue by bigdataage** [biogo/biogo#25]
Where is the documentation of bioGo?
How can I use biogo to analysis NGS data?
Which functions have been available?
Thanks!

**Comment by kortschak** [comment]
> Where is the documentation of bioGo?

The documentation is available [via godoc.org](http://godoc.org/?q=biogo) or locally. This will also show you what is avilable.

> How can I use biogo to analysis NGS data?

This is a very broad question and not entirely appropriate for a bug tracker. There is a user mailing list for this kind of thing (I should add that back to the README).
