### ISSUE TITLE
align: add semi-global alignment

### ISSUE THREAD

**Issue by josharian** [biogo/biogo#33]
I recently wrote a NW implementation with penalty-free end gaps for semi-global alignment, before I discovered biogo. Any interest in accepting such a thing, if contributed? (I just want to check in before putting in much effort.)

**Comment by kortschak** [comment]
Sure. How is it parameterised? and how do you think the API would fit with the current aligners?

Also, I'm curious about the recent interest in this domain.

**Comment by josharian** [comment]
"Penalty-free end gaps" is naturally a bool (i.e. no parameters beyond on/off).

I'm not sure about how the API would fit with the current aligners. I'd hate to have combinatorial explosion. I'd like to do something like [functional options](dave.cheney.net/2014/10/17/functional-options-for-friendly-apis), which is the API approach I roughed out for my personal NW implementation. That doesn't play nicely with the existing API, though. I'll think about it and come back with a proposal.

I'll email you about the recent interest.

**Comment by josharian** [comment]
My attention has now moved elsewhere. Since I'm the only person who wants this right now, and the API options are poor, I'm going to close this for now.

If any future person wants to add it, https://github.com/josharian/biogo/commit/34b8e96bd83b2a506cfc8762309520be9e7ffed3 might be somewhat useful.
