### ISSUE TITLE
io/seqio: add ab1 parser

### ISSUE THREAD

**Issue by josharian** [biogo/biogo#34]
I recently wrote a rudimentary ab1 parser. Interest in having it contributed? There are some API questions, but I'm sure that they could be sorted.

**Comment by kortschak** [comment]
We probably wouldn't use it (mainly we're Illumina and PB), but I'm sure others might, so sure.

thanks

**Comment by josharian** [comment]
Ok. Will toss up an API proposal here at some point over the coming weeks. The code itself is very simple.

**Comment by kortschak** [comment]
I'm thinking this might want to go in a subrepo - ab? (similar to the illumina subrepo).

**Comment by josharian** [comment]
Probably.

**Comment by josharian** [comment]
I'm not going to see this through. If anyone else wants to, there's a working implementation at https://github.com/josharian/abif that you are welcome to hijack, improve, and adapt for biogo compatibility. In the meantime, I'm going to close this. Thanks for the discussion, @kortschak.
