### ISSUE TITLE
The orientation of a feature should not be defined relative to its location.

### ISSUE THREAD

**Issue by mnsmar** [biogo/biogo#40]
**Background**
I tried to get the 5'UTR from a transcript. The `UTR5start()`and `UTR5end()` functions check the transcript orientation to decide where the 5'end is. This is wrong as seen in the example below. Notice that the transcript orientation is `Forward` because it's defined on a gene and this results in the wrong identification of the 5'end (returns the 3'end instead of the 5'end).

```
Transcript:          3'<------------5'       Forward
Gene:              <---------------------    Reverse
Chrom:       -----------------------------------
```

**Suggestion**
I thought about this and realized that the problem is not the function implementation. The problem is that the transcript does not have the required information and the only option is to look down the feature chain.

If we think of the oriented feature as a vector, the notation for its coordinates would be `[x1, x2]` where the first number is the start of the vector and the second number is the end of the vector. Examples: 
A: `[10, 20]`
B: `[20, 10]`
In this notation we can easily see that B is the reverse of A. In other words, the orientation is an invariant of the notation. If the coordinate system changes, then the actual numbers might change but the first number would always be the start and the second number the end of the vector. 

Instead, in biogo we use a different notation like so:
A: `[10, 20], Forward`
B: `[10, 20], Reverse`

Therefore, I think it's not correct to define the orientation as `// Orientation returns the orientation of the feature relative to its location.`. Instead we should use `// Orientation returns the orientation of the feature.` and make it clear in the documentation what this actually means and that it does not depend on the feature location. This will probably result in some code changes but I think it is required.

Any thoughts?

**Comment by kortschak** [comment]
The issue is that the current definition is a simple invariant. I'd really like to keep it like that. The alternative is too loosely defined and makes the use of Orientation more difficult. If it can be fixed by changing the code of the functions in question I would prefer that approach.

**Comment by mnsmar** [comment]
> The issue is that the current definition is a simple invariant.

Is it correct though? Cause when we go from the "vector notation" to the "biogo notation", we are pushing the directionality information down the hierarchy. It's equivalent to changing the order of the `[x1, x2]` in the "vector notation" and letting `x1` mean the start of the vector one time and the end of the vector another time.

> The alternative is too loosely defined and makes the use of Orientation more difficult

We could define it along the following `Orientation returns the orientation of the feature which is either from Start to End or from End to Start.`. Do you think that something like this is still too loose?

> If it can be fixed by changing the code of the functions in question I would prefer that approach.

I can't think of any way to fix this except to follow the Location() chain to find the base orientation and decide based on that. However, I think this is a code smell and I don't really like it. I'm afraid that this is gonna bite us at some point. Like, what happens if in a 3 chain feature we delete the last feature? Then all the coordinates of the first and second feature remain consistent except for the orientation.

**Comment by kortschak** [comment]
> We could define it along the following `Orientation returns the orientation of the feature which is either from Start to End or from End to Start.`. Do you think that something like this is still too loose?

It's not too loose, but it's something I really don't want to do. A nice invariant that features have is that `start <= end`. This make incorrectness easy to find. Just from a work perspective, it would break a lot of code to change that, but from a reviewability perspective, it complicates things.

There is no vectorial semantics in a bíogo feature except that start comes before end. The arrangement of the fields is not defined and in fact, one or both of them may be missing. Having spent too much time with broken feature description formats I don't want to add ambiguity to this one.

**Comment by mnsmar** [comment]
I don't think I made myself clear. I don't argue against the invariant that `start <= end`. I like this, and that's the way it should be for all the reasons that you mentioned. I'm just saying that the orientation should illustrate the direction of the feature independently of the location. Otherwise an oriented feature is not self consistent. I believe that this is something we will need to fix sooner than later. As for the code, my feeling is that very few things are gonna change. We can discuss it after/if we agree on the issue. I agree that if it breaks a lot of code then we should not proceed.

**Comment by kortschak** [comment]
> I'm just saying that the orientation should illustrate the direction of the feature independently of the location.

I guess this is what I'm not understanding.

If you could put together some code that demonstrates how you think it should be done, then I can think about that.

One of the things that I like about the current approach is that the orientation discovery parallels the range discovery.

It seems to me that the UTR finding functions _should_ be traversing the chain until the reach the transcript level (defined either as a parameter or via some heuristic).

**Comment by mnsmar** [comment]
```
Transcript:            10 <------------ 20
Gene:             100 <--------------------- 130
Chrom:       ---------------------------------------
```

On the example above our current approach is:

```
t.Start() == 10, t.End()==20, t.Orientation()==Forward, t.Location() == g
g.Start() == 100, g.End()==130, g.Orientation()==Reverse, g.Location() == chrom
```

I suggest that it should be

```
t.Start() == 10, t.End()==20, t.Orientation()==Reverse, t.Location() == g
g.Start() == 100, g.End()==130, g.Orientation()==Reverse, g.Location() == chrom
```

In the new approach, the semantics is that the orientation simply shows if the feature has direction from `Start()` to `End()` or from `End()` to `Start()`. Obviously Reverse means that the direction is from `End()` to `Start()`. In contrast to our current approach, notice that in the new approach the transcript is self consistent even if you delete the gene.

> One of the things that I like about the current approach is that the orientation discovery parallels the range discovery.

Yes, but I am not sure they are actually the same thing. Conceptually, Start() and End() assume that there is an underlying Location() on which they are defined (though for simplicity we also allow the Location() to be nil). However, the Orientation() is a different story. It makes perfect sense to define an Orientation() even if the underlying Location() does not exist.

**Comment by kortschak** [comment]
OK. Thank you for that, it clarifies it nicely.

I am not convinced that this can't still be done with the current API. The reservation I have is that this new approach will break the way `.../biogo/graphics/rings` handles orientations of features. It is possible for any feature to know its orientation in both cases with reference to the feature chain; I don't think orientation actually does make sense absent a location.

**Comment by mnsmar** [comment]
It can be done with the current API but I think it's not the proper way for the reasons I explained earlier. I think its dangerous to have an instance (e.g. transcript) that depends on the state of other instances (e.g. gene) for its consistency. It's a code smell which if we can properly solve for good I would prefer it.

> I don't think orientation actually does make sense absent a location.

Probably the simplest way to think about it is to consider a feature on a nil location. What does Start() and End() mean in this case. As long as they preserve the length, their actual values are _irrelevant_ for the transcript behavior. On the other hand, the orientation is well defined. The value of the Orientation affects the transcript behavior. For example, it shows were is the 5' end.

> The reservation I have is that this new approach will break the way .../biogo/graphics/rings handles orientations of features. 

This is something that you know much better than me. The only thing I can argue is that in `...biogo/biogo/...` we probably won't have to change a single line of code, except the docs. This will probably give ample time to other packages to adapt to the new semantics without breaking anything.

P.S. Does biogo have any strategy for backwards incompatible changes? For example, mark code deprecated and remove after some time.

**Comment by kortschak** [comment]
I need to think about this more.

> Does biogo have any strategy for backwards incompatible changes? For example, mark code deprecated and remove after some time.

Yes. Don't make them if at all possible.

**Comment by kortschak** [comment]
Essentially this boils down to an intrinsic difficulty in dealing with what "start" and "end" mean. In various places they mean different things and trying to cover all those (potentially contradictory) semantics I think is a fool's errand.

The approach taken in bíogo is that start and end are always relative to the base coordinate system, which may result in the 5' end of a CDS being specified by the `End` method and the 3' end being described by the `Start` method. I don't think it is necessary to make features exist independently of their locations - this was an intentional design decision when I was thinking about features.

The reason I went with the approach of a consistent coordinate system (which does I think parallel the orientation API) is the ease of getting coordinate right - something I've seen happen horribly wrongly in other approaches.

Maybe I've still missed what you are saying, so please correct me if I have.

**Comment by mnsmar** [comment]
> I don't think it is necessary to make features exist independently of their locations - this was an intentional design decision when I was thinking about features.

Yes but there is always at least one feature, the base, which exists independently of a location. And if you remember we had lots of trouble to properly design `BaseOrientationOf()` and `OrientationWithin()` in #29 and #30 and I think the reason is what is described in this issue. (BTW these two functions become obsolete in the suggested design.)

I agree it's all about design decisions that lead to better and easier to maintain code for the majority (possibly not all) of use cases. But I don't see why the current design, as far as the orientation goes (the start and end are fine), is better than the alternative. On the contrary, I think it leads to tight [coupling](https://en.wikipedia.org/wiki/Coupling_%28computer_programming%29) and worst performance. Apart from this, I don't think I have more to add in favor of one or the other so unless you have something to add I think we can close the issue.

**Comment by kortschak** [comment]
> Yes but there is always at least one feature, the base, which exists independently of a location.

This reflects the biology where transcripts and chromosomes are free floating and have no globally definable orientation.

It's true that having to look through a feature chain impacts on performance, but it is easy to cache that work (this is what I do). The converse of the coupling claim is the argument for data normalisation which is what is happening here.

The UTR methods do need to be fixed though.

**Comment by mnsmar** [comment]
Yes I will open a PR to fix them.

**Comment by kortschak** [comment]
@mnsmar Can this be closed?

**Comment by mnsmar** [comment]
Yes. Thanks
