### ISSUE TITLE
RevComp on Slice

### ISSUE THREAD

**Issue by ryanking** [biogo/biogo#53]
Is there a reason there's no RevComp on alphabet.Slice?

**Comment by kortschak** [comment]
An alphabet can be any set of letters. Not all letters have complementarity, e.g. amino acids.

**Comment by ryanking** [comment]
That makes sense (I'm a software engineer, new to bio). Sorry I didn't see a mailing list or other place to ask for help.

Here's what I'm trying to do, maybe you can point me in a good direction–

I have a number of DNA Seq's for which I need to pull out slices based on a pattern. I need to match that pattern in both directions and then emit them all in the forward direction.

I was trying to do this with Slice, but then I end up not being able to RevComp them. Is building my own RevComp for alphabet.Letters the best way to do this?

**Comment by kortschak** [comment]
Use [`linear.Seq`](https://godoc.org/github.com/biogo/biogo/seq/linear#Seq) or [`linear.QSeq`](https://godoc.org/github.com/biogo/biogo/seq/linear#QSeq) depending on whether they have quality information. Use [`segio/fasta`](https://godoc.org/github.com/biogo/biogo/io/seqio/fasta) or [`seqio/fastq`](https://godoc.org/github.com/biogo/biogo/io/seqio/fastq) to read them in.
