### ISSUE TITLE
align: improve documentation for accessing alignment scores

### ISSUE THREAD

**Issue by bsipos** [biogo/biogo#57]
In the structure holding the pairwise alignment results in biogo/align/align.go the alignment score is not exported and the featPair type is private to the package.

`type featPair struct {
	a, b  feature
	score int
}
`
As the alignment methods return []feat.Pair, there is no way to access the alignment score as far as can I see. Is that right? If yes, it would be nice to have a way to do that (other than parsing the string representation of the featPair objects).

**Comment by kortschak** [comment]
Yeah, sorry. This was a pretty unfortunate API design decision. It has been there for a long time though, so I don't think that I can change it.

It's not as bad as you might think though. The `featPair` type implements [`Score() int`](https://github.com/biogo/biogo/blob/2fcb9b14416ac1572368eca0e5c1394594930375/align/align.go#L127) which means that if you assert to `interface{ Score() int }` you can get that information.

This should probably be documented better.

**Comment by bsipos** [comment]
Thanks! Asserting a "Scorer" interface works for accessing the alignment score.

**Comment by comatrion** [comment]
@bsipos, @kortschak could you elaborate a little more on this please

I have tried
```
        aln, _ := needle.Align(nwsa, nwsb)
        fmt.Printf("%s\n", aln)
        fmt.Println(reflect.TypeOf(aln[0])
```
giving
```
[[0,4)/-=-5 [4,7)/[0,3)=3 [7,32)/-=-26 [32,34)/[3,5)=2 [34,43)/-=-10]
*align.featPair
```
This looks promising. I see the expected type `*align.featPair` which I can see has the exported `Score` method.

So following previous posts I tried defining a Scorer interface like this
```
type Scorer interface {
        Score() int
}
```
however
```
        fmt.Println(aln[0].Scorer())
```
throws
```
./main.go:46:35: aln[0].Scorer undefined (type feat.Pair has no field or method Scorer)
```
Here I see type `feat.Pair` which does not have the `Score` method defined.

**Comment by kortschak** [comment]
Yeah, I'm sorry about that. The API is not nice. In your call, you need to write `fmt.Println(aln[0].(Scorer).Score())`.

**Comment by zorino** [comment]
@kortschak  similarly how could I extract the positions of each features to compute gap sizes ?

**Comment by kortschak** [comment]
You need to walk the slice of alignment features. The `feat.Pair`s with one half with length 0 are gaps.
