### ISSUE TITLE
Issues about filter BAM record 

### ISSUE THREAD

**Issue by ygidtu** [biogo/biogo#72]
Hi,
    First of all, thanks for all this amazing work. Recentlly I trying to filter some records out of a valid BAM file, But I can't deal with the headers properly.  The code I used are as follow. BTW I also trying to create a new sam.Header, but really can't figure out how to do it

```
f, err = os.Open(input_bam)
	if err != nil {
		log.Fatalf("could not open file %q:\n", err)
	}
	defer f.Close()
	ok, err := bgzf.HasEOF(f)
	if err != nil {
		log.Fatalf("could not open file %q:\n", err)
	}
	if !ok {
		log.Printf("file %q has no bgzf magic block: may be truncated\n", input_bam)
	}

	b, err := bam.NewReader(f, threads)
	if err != nil {
		log.Fatalf("could not read bam: %q\n", err)
	}
	defer b.Close()


	fo, err := os.OpenFile(output_bam, os.O_WRONLY|os.O_CREATE, os.ModeAppend)
	defer fo.Close()
	if err != nil {
		log.Fatalf("Could open file %v\n", output_bam)
	}
        
        // due to I need a header exactlly matches with BAM records, so I trying to filter out header Refs here
	header := b.Header().Clone()

	removedRef := make([]*sam.Reference, 0)
	for _, i := range header.Refs() {
		if _, ok := rna[i.Name()]; !ok {
			removedRef = append(removedRef, i)
		}
	}

	for _, i := range removedRef {
		err = header.RemoveReference(i)
		if err != nil {
			log.Fatalf("remove header reference failed, %v\n", err)
		}
	}

	w, err := bam.NewWriter(fo, header, threads)
	if err != nil {
		log.Fatalf("Could write file %v\n", f)
	}
	defer w.Close()

	// And iter all BAM records
	for {
		rec, err := b.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatalf("error reading bam: %v", err)
		}

		if _, ok := rna[rec.Ref.String()]; ok {
			err = w.Write(rec)

			if err != nil {
				log.Fatalf(err.Error())
			}
		}

	}
```

**Comment by ygidtu** [comment]
Thanks for your answer, and so sorry for the troubles that I made.

**Comment by kortschak** [comment]
It's no trouble. Did the answer work?

**Comment by ygidtu** [comment]
Sorry for late response, I manage to create a new header, and write the qualified headers and records into the new file, seems this file is fine now.

**Comment by ygidtu** [comment]
The strange thing is I create a new header and new record based on the original. When I look at the output BAM content using `samtools view`， there always a `truncated file` label inside of it
![default](https://user-images.githubusercontent.com/29178828/50448981-44a94d80-095f-11e9-83c3-bcec67189591.png)

Part of my code:
```go
// new header
refs := make([]*sam.Reference, 0)
text := make([]byte, 0)
for _, i := range b.Header().Refs() {
	if _, ok := rna[i.Name()]; ok {
		refUrl, err := url.Parse(i.URI())
		check(err)
		j, err := sam.NewReference(i.Name(), strconv.Itoa(i.ID()), i.Species(), i.Len(), i.MD5(), refUrl)
		check(err)

		refs = append(refs, j)
	}
}

header, err := sam.NewHeader(text, refs)
check(err)


// new record and write
newRec, err := sam.NewRecord(
	rec.Name,
	rec.Ref,
	rec.MateRef,
	rec.Pos,
	rec.MatePos,
	rec.Len(),
	rec.MapQ,
	rec.Cigar,
	rec.Seq.Expand(),
	rec.Qual,
	rec.AuxFields,
	)

err = header.Validate(newRec)
check(err)

err = w.Write(newRec)
check(err)
```

**Comment by kortschak** [comment]
Are you calling `Close` n the `bam.Writer`? This will write the BGZF EOF block.

**Comment by ygidtu** [comment]
Yes, I tries defer or manully Close, both will produce this results. And no errors.

**Comment by kortschak** [comment]
Are you calling `Close` on the `os.File`? (Do you have a complete self-contained reproducer?)

**Comment by kortschak** [comment]
I can't see a problem with that, but it's not a complete self-contained reproducer. I can't debug this without a runnable program that fails (with embedded data).

**Comment by ygidtu** [comment]
Understand, I'll see if I can fix this or make a reproducible sample for you. Thank for your help again
