### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by DanielRivasMD** [biogo/biogo#84]
### Background
Library is great for manipulating biological data. On target!

### Proposal
However, examples on how to implement functions and types are virtually non-existent. Could you add more examples, please?

I'm particularly having trouble writing fasta sequences. Appreciated. Cheers

**Comment by kortschak** [comment]
The best place to look is in https://github.com/biogo/examples. I'm no longer actively involved in bioinformatics work, so I will not be able to find the time to add further examples.

**Comment by DanielRivasMD** [comment]
Thanks for your response. I'll check it out and close the issue then.
