### ISSUE TITLE
Read + and FFFF 

### ISSUE THREAD

**Issue by YspCoder** [biogo/biogo#87]
@A00202:643:HF5W5DSXY:2:1101:2013:1000 1:N:0:AGCCTATC
CCTCCTTAGGCAACCTGGTGGTCCCCCGCTCCCGGGAGGTCACCATATTGATGCCGAACTTAGTGCGGACACCCGATCGGCATAGCGCACTACAGCCCAGAACTCCTGGACTCAAGCGATCCTCCTGTCTCAGCCTCCCGAGTAGCTGGG
+
,FF:FFFF,FFFFF,F::FFFFFFFFFF,FFFFFFFFF:FFF:F:FFF:FFFFFFF:F:FFF,F:FF:FFF:FFFFFF:::FFFFFF:FFFF:FFFF,FFF,,:FFF::FFFFFFF,FFFF,FFFFFFFFFFFFFFFFFFFFFFF,FF:F

Hello, I want to read + and FFFF

**Comment by kortschak** [comment]
https://pkg.go.dev/github.com/biogo/biogo@v1.0.4/io/seqio/fastq and https://github.com/biogo/biogo/blob/a5b3a035c11da8cdd2f262613ed9354c813c2697/io/seqio/seqio_test.go#L430-L444 should help you here.

**Comment by YspCoder** [comment]
Hello, I used the following method by looking through the source code of the fastq tool, but the reading speed and efficiency are average
```
func q(s *linear.QSeq, rc int) string {
	v := make([]byte, 0, s.Len())
	if rc == 1 {
		for i := 0; i < s.Len(); i++ {
			v = append(v, []byte{s.At(i).Q.Encode(alphabet.Sanger)}...)
		}
	} else {
		for i := s.Len() - 1; i >= 0; i-- {
			v = append(v, []byte{s.At(i).Q.Encode(alphabet.Sanger)}...)
		}
	}
	return string(v)
}
```
