### ISSUE TITLE
feat.Pair dont have "Score() int" interface memeber. So feat.pair "Score" function cant be called.

### ISSUE THREAD

**Issue by sis6789** [biogo/biogo#88]
### What did you do?
func TestSW_Align(t *testing.T) {

	s1 := `TTTCTCATCT`
	s2 := `GGCCATCTTGGCTCCTCCC`
	sws1 := &linear.Seq{Seq: alphabet.BytesToLetters([]byte(s1))}
	sws1.Alpha = alphabet.DNAgapped
	sws2 := &linear.Seq{Seq: alphabet.BytesToLetters([]byte(s2))}
	sws2.Alpha = alphabet.DNAgapped

	smith := SW{
		{2, -1, -1, -1, -1},
		{-1, 2, -1, -1, -1},
		{-1, -1, 2, -1, -1},
		{-1, -1, -1, 2, -1},
		{-1, -1, -1, -1, 0},
	}
	result, _ := smith.Align(sws1, sws2)
	for ix, v := range result {
		fmt.Printf("%#v\n", v.Score())
		fmt.Println(ix, v.Features()[0].Start(), v.Features()[0].End(), v.Features()[0].Len())
		fmt.Println(ix, v.Features()[1].Start(), v.Features()[1].End(), v.Features()[1].Len())
	}
	status := fmt.Sprint(result)
	fmt.Printf("%#v\n", status)

}

### Solution
at feature.go:97, add "Score() int"

type Pair interface {
	Features() [2]Feature
	**Score() int     <==================**
}

### What did you expect to happen?
v.Score() return matching score.
But GO does not permit v.Score() function call.

### What actually happened?
compile error!

### What version of Go and bíogo are you using?
go v1.75, biogo latest

### Does this issue reproduce with the current master?
yes!

**Comment by kortschak** [comment]
This is an unfortunate design decision that can't be changed due to backwards compatibility requirements. The solution is to type assert to `type interface{ Score() int }` and use that asserted value to obtain the score.

```
for ix, v := range result {
	type scorer interface{ Score() int }
	fmt.Printf("%#v\n", v.(scorer).Score())
	fmt.Println(ix, v.Features()[0].Start(), v.Features()[0].End(), v.Features()[0].Len())
	fmt.Println(ix, v.Features()[1].Start(), v.Features()[1].End(), v.Features()[1].Len())
}
```
